Sil\Bundle\EmailBundle\Entity\EmailTemplate:
    type: entity
    table: sil_email_template
    fields:
        name:
            type: string
            nullable: false
        content:
            type: text
