Sil\Bundle\EmailBundle\Entity\EmailLink:
    type: entity
    table: sil_email_link
    fields:
        destination:
            type:    text
        address:
            type:    string
        date:
            type:    datetime
            nullable: true
    manyToOne:
        email:
            targetEntity: Sil\Bundle\EmailBundle\Entity\EmailInterface
            inversedBy: links
            joinColumn:
                name: email_id
            cascade: [ persist ]
