Sil\Bundle\EmailBundle\Entity\Email:
    type: mappedSuperclass
    blast:
        loggable: true
    fields:
        field_from:
            type:       string(255)
            nullable:   false
        field_to:
            type:       string(255)
            nullable:   false
        field_cc:
            type:       string(255)
            nullable:   true
        field_bcc:
            type:       string(255)
            nullable:   true
        field_subject:
            type:       string(255)
            nullable:   true
        content:
            type:       text
            nullable:   true
        textContent:
            type:       text
            nullable:   false
        sent:
            type:       boolean
            nullable:   true
        tracking:
            type:       boolean
            nullable: true
    manyToMany:
        attachments:
            targetEntity: Sil\Bundle\MediaBundle\Entity\FileInterface
            joinTable:
                name: sil_email_file
                joinColumns:
                    email_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    file_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                        unique: true
            cascade: [persist, remove]
            orphanRemoval: true
    oneToMany:
        receipts:
            targetEntity: Sil\Bundle\EmailBundle\Entity\EmailReceipt
            mappedBy: email
            cascade: [persist, merge, remove]
            orphanRemoval:  true
        links:
            targetEntity: Sil\Bundle\EmailBundle\Entity\EmailLink
            mappedBy: email
            cascade: [persist, merge, remove]
            orphanRemoval:  true
    oneToOne:
        template:
          targetEntity: Sil\Bundle\EmailBundle\Entity\EmailTemplate
          joinColumn:
            name: template_id
            referencedColumnName: id
