imports:
    - { resource: admin/sil_email.admin.email.yml}
    - { resource: admin/sil_email.admin.email_template.yml}
    - { resource: admin/sil_email.admin.email_receipt.yml}
    - { resource: admin/sil_email.admin.email_link.yml}
