services:
    sil_email.sender:
        class: Sil\Bundle\EmailBundle\Services\Sender
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sil_email.tracking'
            - '@sil_email.inline_attachments'
            - '@swiftmailer.mailer.direct_mailer'
            - '@swiftmailer.mailer.spool_mailer'
            - '@sil.email.address_manager'

    sil_email.tracking:
        class: Sil\Bundle\EmailBundle\Services\Tracking
        arguments: [ '@router' ]

    sil_email.stats:
        class: Sil\Bundle\EmailBundle\Services\EmailStats

    sil_email.inline_attachments:
        class: Sil\Bundle\EmailBundle\Services\InlineAttachments

    sil.email.address_manager:
        class: Sil\Bundle\EmailBundle\Services\AddressManager

### SwiftMailer database spool ###
    swiftmailer.mailer.spool_mailer.spool.db:
        class: Sil\Bundle\EmailBundle\Services\SwiftMailer\Spool\DbSpool
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '%kernel.environment%'
### SONATA BLOCKS ###

    sil.email.block.emails_list:
        class: Sil\Bundle\EmailBundle\Block\EmailsListBlock
        arguments:
            - 'sil.email.block.emails_list'
            - '@templating'
        calls:
            - [setManager, ['@doctrine.orm.entity_manager']]
        tags: [{ name: sonata.block }]
