services:
    blast_core.label.strategy.librinfo_email:
        class: Blast\Bundle\CoreBundle\Translator\LibrinfoLabelTranslatorStrategy
        arguments: ['Sil\Bundle\EmailBundle']
    
    librinfo_email.sender:
        class: Sil\Bundle\EmailBundle\Services\Sender
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@librinfo_email.tracking'
            - '@librinfo_email.inline_attachments'
            - '@swiftmailer.mailer.direct_mailer'
            - '@swiftmailer.mailer.spool_mailer'
            - '@librinfo.email.address_manager'

    librinfo_email.tracking:
        class: Sil\Bundle\EmailBundle\Services\Tracking
        arguments: [ '@router' ]

    librinfo_email.stats:
        class: Sil\Bundle\EmailBundle\Services\EmailStats

    librinfo_email.inline_attachments:
        class: Sil\Bundle\EmailBundle\Services\InlineAttachments

    librinfo.email.address_manager:
        class: Sil\Bundle\EmailBundle\Services\AddressManager

### SwiftMailer database spool ###
    swiftmailer.mailer.spool_mailer.spool.db:
        class: Sil\Bundle\EmailBundle\Services\SwiftMailer\Spool\DbSpool
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '%kernel.environment%'
### SONATA BLOCKS ###

    librinfo.email.block.emails_list:
        class: Sil\Bundle\EmailBundle\Block\EmailsListBlock
        arguments:
            - 'librinfo.email.block.emails_list'
            - '@templating'
        calls:
            - [setManager, ['@doctrine.orm.entity_manager']]
        tags: [{ name: sonata.block }]
