
services:
    sil_email.admin.email_template:
        class: Sil\Bundle\EmailBundle\Admin\EmailTemplateAdmin
        arguments: [~, "%sil_email.entity.email_template.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.email.menu_label.email_template
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [edit, SilEmailBundle:CRUD:email_edit.html.twig]]
