
services:
    sil_email.admin.email_link:
        class: Sil\Bundle\EmailBundle\Admin\EmailLink
        arguments: [~, "%sil.model.email_email_link.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.email.menu_label.email_link
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
