
services:
    sil_email.admin.email:
        class: Sil\Bundle\EmailBundle\Admin\EmailAdmin
        arguments: [~, "%sil_email.entity.email.class%", SilEmailBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.emailbundle.admin.email
              label_translator_strategy: blast_core.label.strategy.sil_email
        calls:
            - [ setTemplate, [edit, SilEmailBundle:CRUD:email_edit.html.twig]]
            - [ setTemplate, [show, SilEmailBundle:CRUD:email_show.html.twig]]
