
services:
    sil_email.admin.email_receipt:
        class: Sil\Bundle\EmailBundle\Admin\EmailReceipt
        arguments: [~, "%sil.model.email_receipt.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.email.menu_label.email_receipt
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
