
services:
    sil_email.admin.email_receipt:
        class: Sil\Bundle\EmailBundle\Admin\EmailReceipt
        arguments: [~, "%sil_email.entity.email_receipt.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.emailbundle.admin.emailreceipt
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
