<?php

/*
 * This file is part of the Blast Project package.
 *
 * Copyright (C) 2015-2017 Libre Informatique
 *
 * This file is licenced under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace Librinfo\EmailBundle\tests\Functional;

/*
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-28 at 14:48:08.
 * Modified by Quotidianus
 */
use PHPUnit\Framework\TestCase;
use Librinfo\EmailBundle\Services\Sender;
use Librinfo\EmailBundle\Entity\Email;

class SenderTest extends TestCase
{
    /**
     * @var Sender
     */
    protected $object;
    private $manager;
    private $tracker;
    private $inlineAttachmentsHandler;
    private $directMailer;
    private $spoolMailer;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->manager = $this->createMock('Doctrine\ORM\EntityManager');
        $this->tracker = $this->createMock('Librinfo\EmailBundle\Services\Tracking');
        $this->inlineAttachmentsHandler = $this->createMock('Librinfo\EmailBundle\Services\InlineAttachments');
        $this->directMailer = $this->createMock('Swift_Mailer');
        /*
         * todo : check if we need to mock for this same object
         */
        $this->spoolMailer = $this->createMock('Swift_Mailer');

        $this->object = new Sender(
                $this->manager, $this->tracker, $this->inlineAttachmentsHandler, $this->directMailer, $this->spoolMailer
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Librinfo\EmailBundle\Services\Sender::send
     *
     * @todo   Implement testSend().
     */
    public function testSend()
    {
        $this->markTestSkipped();
        $email = new Email();
        $this->object->send($email);

        $this->assertFileExists($this->inlineAttachmentsHandler);
    }
}
