services:
    librinfo_email.admin.email:
        class: Librinfo\EmailBundle\Admin\EmailAdmin
        arguments: [~, Librinfo\EmailBundle\Entity\Email, LibrinfoEmailBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Email }
        calls:
            - [ setTemplate, [edit, LibrinfoEmailBundle:CRUD:email_edit.html.twig]]
            - [ setTemplate, [show, LibrinfoEmailBundle:CRUD:email_show.html.twig]]
            
    librinfo_email.admin.email_template:
        class: Librinfo\EmailBundle\Admin\EmailTemplateAdmin
        arguments: [~, Librinfo\EmailBundle\Entity\EmailTemplate, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EmailTemplate }
        calls:
            - [ setTemplate, [edit, LibrinfoEmailBundle:CRUD:email_template_edit.html.twig]]

    librinfo_email.admin.email_receipt:
        class: Librinfo\EmailBundle\Admin\EmailReceiptAdmin
        arguments: [~, Librinfo\EmailBundle\Entity\EmailReceipt, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EmailReceipt }

    librinfo_email.admin.email_link:
        class: Librinfo\EmailBundle\Admin\EmailLinkAdmin
        arguments: [~, Librinfo\EmailBundle\Entity\EmailLink, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EmailLink }
